name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build release archive
        run: |
          mkdir -p dist
          python3 - <<'PY'
import subprocess
import pathlib
import zipfile
dist_dir = pathlib.Path('dist')
archive_path = dist_dir / 'EDMC-Mining-Analytics.zip'
result = subprocess.run(
    [
        'git',
        'ls-files',
        '--cached',
        '--others',
        '--exclude-standard',
        '-z',
    ],
    check=True,
    capture_output=True,
)
file_list = [path for path in result.stdout.split(b'\0') if path]
with zipfile.ZipFile(archive_path, 'w', compression=zipfile.ZIP_DEFLATED) as zf:
    for raw_path in file_list:
        path_str = raw_path.decode('utf-8')
        zf.write(path_str, arcname=path_str)
PY
      - name: Upload archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: EDMC-Mining-Analytics
          path: dist/EDMC-Mining-Analytics.zip
      - name: Attach archive to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/EDMC-Mining-Analytics.zip
